// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atlas-ledger/AtlasLedger.tsx": () => import("../components/mockups/atlas-ledger/AtlasLedger.tsx"),
  "./components/mockups/templates/RustArchitectureSignup-oVEKDB/App.tsx": () => import("../components/mockups/templates/RustArchitectureSignup-oVEKDB/App.tsx")
};
